tasks:
  - init: echo "Workspace Ready"
    command: echo "Replace me with omething that should run on every start, or just
      remove me entirely."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - CristianRengifo.informix4gl@0.0.10:4D5XLQ0fKUPo6Mc2gtur5A==