image:
  file: .gitpod.Dockerfile
  
tasks:
  - init: echo "Workspace Ready"
    command: sudo bash install_informix.sh


vscode:
  extensions:
    - CristianRengifo.informix4gl@0.0.10:4D5XLQ0fKUPo6Mc2gtur5A==
